POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Gaston",
    "email": "gdelucchi@me.com",
    "password": " "
}
###
POST http://localhost:3000/users/gas?saludo=hola&&comision=39750
Content-Type: application/json

{
    "first_name": "Gaston",
    "email": "gdelucchi@me.com",
    "password": "12345"
}
###
