apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeclase36
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeclase36
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeclase36
  template:
    metadata:
      labels:
        app: kubeclase36
    spec:
      containers:
        - name: kubecontainer
          image: gadelucchi/clase36:1.0.0
          ports: 
            - containerPort: 8080
          env: 
            - name: MONGO_URL_LOCAL
              value: mongodb+srv://GADelucchi:jxDkAb8tanYj2L1x@cluster0.nxdvhds.mongodb.net/ecommerce
          imagePullPolicy: Always