config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - name: 'Sessions Flow (register + login)'
    flow:
      - log: 'Creando usuario de prueba'
      - get:
          url: '/pruebas/testuser'
          capture:
            - json: '$.username'
              as: 'username'
            - json: '$.first_name'
              as: 'first_name'
            - json: '$.last_name'
              as: 'last_name'
            - json: '$.email'
              as: 'email'
            - json: '$.password'
              as: 'password'
      - log: 'Registramos el usuario'
      - post:
          url: '/api/session/register'
          json:
            username: "{{username}}"
            first_name: "{{fisrt_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            password: "{{password}}"
      - think: 2
      - log: 'Login user'
      - post:
          url: '/api/session/login'
          json:
            email: "{{email}}"
            password: "{{password}}"